Added outcome property

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,12 +25,8 @@ jobs:
         run: |
           set +e
           a=`head -1 $GITHUB_WORKSPACE/Jenkinsfile | grep arun | wc -l`
-          if [ $a -ne 1 ]; then echo "not found"; echo ::set-output name=exit_status::1; else echo "found"; echo ::set-output name=exit_status::0; fi
+          if [ $a -ne 1 ]; then echo "not found"; exit 1; else echo "found"; fi
         id: find_arun
       - name: error code
-        if: steps.find_arun.outputs.exit_status  !=0
+        if: steps.find_arun.outcome == 'failure'
         run: exit 1
-
-      - name: error code positive
-        if: steps.find_arun.outputs.exit_status == 0
-        run: exit 0
